"""
oracle_db.py
Camada de integração Oracle para a ETAPA 6 do Sistema de Apoio à Decisão.

Escopo atual:
- detectar disponibilidade do driver oracledb
- abrir e fechar conexão
- criar tabelas
- CRUD básico para talhões e colheitas
- sincronizar dados entre memória e Oracle

Observação:
- o sistema continua funcionando sem Oracle; nesse caso, apenas o submenu
  de banco ficará indisponível.
"""

from __future__ import annotations

from typing import Any

try:
    import oracledb  # type: ignore
except ImportError:  # pragma: no cover - depende do ambiente do usuário
    oracledb = None


# -----------------------------------------------------------------------------
# Disponibilidade e conexão
# -----------------------------------------------------------------------------

def driver_disponivel() -> bool:
    """Informa se o driver oracledb está disponível no ambiente."""
    return oracledb is not None



def conectar_oracle(usuario: str, senha: str, dsn: str):
    """Abre uma conexão Oracle usando o driver oracledb."""
    if not driver_disponivel():
        raise RuntimeError(
            "O driver 'oracledb' não está instalado neste ambiente. "
            "Instale com: pip install oracledb"
        )

    return oracledb.connect(user=usuario, password=senha, dsn=dsn)



def fechar_conexao(conexao) -> None:
    """Fecha a conexão Oracle se existir."""
    if conexao is not None:
        conexao.close()


# -----------------------------------------------------------------------------
# Criação de estruturas
# -----------------------------------------------------------------------------

SQL_CRIAR_TABELA_TALHOES = """
CREATE TABLE talhoes (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(50) NOT NULL UNIQUE,
    area_ha       NUMBER(10,2) NOT NULL,
    variedade     VARCHAR2(30) NOT NULL,
    data_plantio  DATE NOT NULL
)
"""

SQL_CRIAR_TABELA_COLHEITAS = """
CREATE TABLE colheitas (
    id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_talhao         NUMBER NOT NULL,
    data_colheita     DATE NOT NULL,
    modo              VARCHAR2(11) NOT NULL,
    producao_ton      NUMBER(10,2) NOT NULL,
    perda_percentual  NUMBER(5,2) NOT NULL,
    perda_toneladas   NUMBER(10,2) NOT NULL,
    umidade_pct       NUMBER(5,2) NOT NULL,
    brix              NUMBER(5,2) NOT NULL,
    meses_plantio     NUMBER(3) NOT NULL,
    CONSTRAINT fk_colheitas_talhoes FOREIGN KEY (id_talhao) REFERENCES talhoes(id)
)
"""



def _tabela_existe(conexao, nome_tabela: str) -> bool:
    """Verifica se a tabela já existe no schema do usuário."""
    cursor = conexao.cursor()
    try:
        cursor.execute(
            "SELECT COUNT(*) FROM user_tables WHERE table_name = :nome",
            nome=nome_tabela.upper(),
        )
        quantidade = cursor.fetchone()[0]
        return int(quantidade) > 0
    finally:
        cursor.close()



def criar_tabelas(conexao) -> list[str]:
    """Cria as tabelas do projeto caso ainda não existam."""
    mensagens: list[str] = []
    cursor = conexao.cursor()
    try:
        if not _tabela_existe(conexao, "talhoes"):
            cursor.execute(SQL_CRIAR_TABELA_TALHOES)
            mensagens.append("Tabela TALHOES criada com sucesso.")
        else:
            mensagens.append("Tabela TALHOES já existe.")

        if not _tabela_existe(conexao, "colheitas"):
            cursor.execute(SQL_CRIAR_TABELA_COLHEITAS)
            mensagens.append("Tabela COLHEITAS criada com sucesso.")
        else:
            mensagens.append("Tabela COLHEITAS já existe.")

        conexao.commit()
        return mensagens
    except Exception:
        conexao.rollback()
        raise
    finally:
        cursor.close()


# -----------------------------------------------------------------------------
# CRUD - Talhões
# -----------------------------------------------------------------------------


def inserir_talhao(conexao, talhao: dict[str, Any]) -> None:
    """Insere um talhão no Oracle preservando o ID da memória."""
    cursor = conexao.cursor()
    try:
        cursor.execute(
            """
            INSERT INTO talhoes (id, nome, area_ha, variedade, data_plantio)
            VALUES (
                :id,
                :nome,
                :area_ha,
                :variedade,
                TO_DATE(:data_plantio, 'YYYY-MM-DD')
            )
            """,
            id=talhao["id"],
            nome=talhao["nome"],
            area_ha=talhao["area_ha"],
            variedade=talhao["variedade"],
            data_plantio=talhao["data_plantio"],
        )
        conexao.commit()
    except Exception:
        conexao.rollback()
        raise
    finally:
        cursor.close()



def listar_talhoes_db(conexao) -> list[dict[str, Any]]:
    """Lista todos os talhões cadastrados no Oracle."""
    cursor = conexao.cursor()
    try:
        cursor.execute(
            """
            SELECT id,
                   nome,
                   area_ha,
                   variedade,
                   TO_CHAR(data_plantio, 'YYYY-MM-DD') AS data_plantio
              FROM talhoes
          ORDER BY id
            """
        )
        registros = []
        for linha in cursor.fetchall():
            registros.append(
                {
                    "id": int(linha[0]),
                    "nome": linha[1],
                    "area_ha": float(linha[2]),
                    "variedade": linha[3],
                    "data_plantio": linha[4],
                }
            )
        return registros
    finally:
        cursor.close()



def atualizar_talhao(conexao, id_talhao: int, nome: str, area_ha: float, variedade: str, data_plantio: str) -> bool:
    """Atualiza um talhão no Oracle."""
    cursor = conexao.cursor()
    try:
        cursor.execute(
            """
            UPDATE talhoes
               SET nome = :nome,
                   area_ha = :area_ha,
                   variedade = :variedade,
                   data_plantio = TO_DATE(:data_plantio, 'YYYY-MM-DD')
             WHERE id = :id
            """,
            id=id_talhao,
            nome=nome,
            area_ha=area_ha,
            variedade=variedade,
            data_plantio=data_plantio,
        )
        conexao.commit()
        return cursor.rowcount > 0
    except Exception:
        conexao.rollback()
        raise
    finally:
        cursor.close()



def excluir_talhao(conexao, id_talhao: int) -> bool:
    """Exclui um talhão do Oracle."""
    cursor = conexao.cursor()
    try:
        cursor.execute("DELETE FROM talhoes WHERE id = :id", id=id_talhao)
        conexao.commit()
        return cursor.rowcount > 0
    except Exception:
        conexao.rollback()
        raise
    finally:
        cursor.close()


# -----------------------------------------------------------------------------
# CRUD - Colheitas
# -----------------------------------------------------------------------------


def inserir_colheita(conexao, colheita: dict[str, Any]) -> None:
    """Insere uma colheita no Oracle preservando o ID da memória."""
    cursor = conexao.cursor()
    try:
        cursor.execute(
            """
            INSERT INTO colheitas (
                id, id_talhao, data_colheita, modo, producao_ton,
                perda_percentual, perda_toneladas, umidade_pct, brix, meses_plantio
            ) VALUES (
                :id, :id_talhao, TO_DATE(:data_colheita, 'YYYY-MM-DD'), :modo, :producao_ton,
                :perda_percentual, :perda_toneladas, :umidade_pct, :brix, :meses_plantio
            )
            """,
            id=colheita["id"],
            id_talhao=colheita["id_talhao"],
            data_colheita=colheita["data_colheita"],
            modo=colheita["modo"],
            producao_ton=colheita["producao_ton"],
            perda_percentual=colheita["perda_percentual"],
            perda_toneladas=colheita["perda_toneladas"],
            umidade_pct=colheita["umidade_pct"],
            brix=colheita["brix"],
            meses_plantio=colheita["meses_plantio"],
        )
        conexao.commit()
    except Exception:
        conexao.rollback()
        raise
    finally:
        cursor.close()



def listar_colheitas_db(conexao) -> list[dict[str, Any]]:
    """Lista todas as colheitas do Oracle com o nome do talhão associado."""
    cursor = conexao.cursor()
    try:
        cursor.execute(
            """
            SELECT c.id,
                   c.id_talhao,
                   t.nome AS nome_talhao,
                   t.area_ha,
                   TO_CHAR(c.data_colheita, 'YYYY-MM-DD') AS data_colheita,
                   c.modo,
                   c.producao_ton,
                   c.perda_percentual,
                   c.perda_toneladas,
                   c.umidade_pct,
                   c.brix,
                   c.meses_plantio
              FROM colheitas c
              JOIN talhoes t ON t.id = c.id_talhao
          ORDER BY c.id
            """
        )
        registros = []
        for linha in cursor.fetchall():
            registros.append(
                {
                    "id": int(linha[0]),
                    "id_talhao": int(linha[1]),
                    "nome_talhao": linha[2],
                    "area_ha": float(linha[3]),
                    "data_colheita": linha[4],
                    "modo": linha[5],
                    "producao_ton": float(linha[6]),
                    "perda_percentual": float(linha[7]),
                    "perda_toneladas": float(linha[8]),
                    "umidade_pct": float(linha[9]),
                    "brix": float(linha[10]),
                    "meses_plantio": int(linha[11]),
                }
            )
        return registros
    finally:
        cursor.close()



def atualizar_colheita(
    conexao,
    id_colheita: int,
    data_colheita: str,
    modo: str,
    producao_ton: float,
    perda_percentual: float,
    perda_toneladas: float,
    umidade_pct: float,
    brix: float,
    meses_plantio: int,
) -> bool:
    """Atualiza uma colheita no Oracle."""
    cursor = conexao.cursor()
    try:
        cursor.execute(
            """
            UPDATE colheitas
               SET data_colheita = TO_DATE(:data_colheita, 'YYYY-MM-DD'),
                   modo = :modo,
                   producao_ton = :producao_ton,
                   perda_percentual = :perda_percentual,
                   perda_toneladas = :perda_toneladas,
                   umidade_pct = :umidade_pct,
                   brix = :brix,
                   meses_plantio = :meses_plantio
             WHERE id = :id
            """,
            id=id_colheita,
            data_colheita=data_colheita,
            modo=modo,
            producao_ton=producao_ton,
            perda_percentual=perda_percentual,
            perda_toneladas=perda_toneladas,
            umidade_pct=umidade_pct,
            brix=brix,
            meses_plantio=meses_plantio,
        )
        conexao.commit()
        return cursor.rowcount > 0
    except Exception:
        conexao.rollback()
        raise
    finally:
        cursor.close()



def excluir_colheita(conexao, id_colheita: int) -> bool:
    """Exclui uma colheita do Oracle."""
    cursor = conexao.cursor()
    try:
        cursor.execute("DELETE FROM colheitas WHERE id = :id", id=id_colheita)
        conexao.commit()
        return cursor.rowcount > 0
    except Exception:
        conexao.rollback()
        raise
    finally:
        cursor.close()


# -----------------------------------------------------------------------------
# Sincronização
# -----------------------------------------------------------------------------


def sincronizar_memoria_para_oracle(conexao, talhoes: list[dict[str, Any]], colheitas: list[dict[str, Any]]) -> dict[str, int]:
    """Insere no Oracle os registros da memória que ainda não existem no banco."""
    ids_talhoes_db = {registro["id"] for registro in listar_talhoes_db(conexao)}
    ids_colheitas_db = {registro["id"] for registro in listar_colheitas_db(conexao)}

    inseridos_talhoes = 0
    inseridos_colheitas = 0

    for talhao in talhoes:
        if talhao["id"] not in ids_talhoes_db:
            inserir_talhao(conexao, talhao)
            inseridos_talhoes += 1

    for colheita in colheitas:
        if colheita["id"] not in ids_colheitas_db:
            inserir_colheita(conexao, colheita)
            inseridos_colheitas += 1

    return {
        "talhoes_inseridos": inseridos_talhoes,
        "colheitas_inseridas": inseridos_colheitas,
    }



def carregar_oracle_para_memoria(conexao) -> dict[str, list[dict[str, Any]]]:
    """Lê talhões e colheitas do Oracle e devolve em formato compatível com a aplicação."""
    return {
        "talhoes": listar_talhoes_db(conexao),
        "colheitas": listar_colheitas_db(conexao),
    }
