CREATE TABLE talhoes (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(50) NOT NULL UNIQUE,
    area_ha       NUMBER(10,2) NOT NULL,
    variedade     VARCHAR2(30) NOT NULL,
    data_plantio  DATE NOT NULL
);

CREATE TABLE colheitas (
    id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_talhao         NUMBER NOT NULL,
    data_colheita     DATE NOT NULL,
    modo              VARCHAR2(11) NOT NULL,
    producao_ton      NUMBER(10,2) NOT NULL,
    perda_percentual  NUMBER(5,2) NOT NULL,
    perda_toneladas   NUMBER(10,2) NOT NULL,
    umidade_pct       NUMBER(5,2) NOT NULL,
    brix              NUMBER(5,2) NOT NULL,
    meses_plantio     NUMBER(3) NOT NULL,
    CONSTRAINT fk_colheitas_talhoes FOREIGN KEY (id_talhao) REFERENCES talhoes(id)
);
