CREATE TABLE COLHEITAS_AGRO (
    ID NUMBER PRIMARY KEY,
    TALHAO VARCHAR2(100) NOT NULL,
    CULTURA VARCHAR2(50) NOT NULL,
    BASE_M NUMBER(10,2) NOT NULL,
    ALTURA_M NUMBER(10,2) NOT NULL,
    AREA_M2 NUMBER(12,2) NOT NULL,
    PRODUCAO_PREVISTA_T NUMBER(12,2) NOT NULL,
    PRODUCAO_REAL_T NUMBER(12,2) NOT NULL,
    PRODUTIVIDADE_T_M2 NUMBER(12,6) NOT NULL,
    PERDA_PERCENTUAL NUMBER(6,2) NOT NULL,
    CLASSIFICACAO_PERDA VARCHAR2(20) NOT NULL,
    DATA_CADASTRO DATE DEFAULT SYSDATE
);
